# Generated by Django 4.2.2 on 2023-12-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_name_city_city_rename_state_city_state_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state_name',
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.state'),
        ),
    ]
